
services:
  deb:
    image: debian13-builder
    working_dir: /home/builder/
    user: builder
    entrypoint: ["/home/builder/workdir/builder/debian-gtk.sh"]
    stdin_open: true
    tty: true
    volumes:
      - ../:/home/builder/workdir
      - ../../plugin-api:/home/builder/plugin-api:ro
  deb-webserver:
    image: debian13-builder
    working_dir: /home/builder/
    user: builder
    entrypoint: ["/home/builder/workdir/builder/debian-webserver.sh"]
    stdin_open: true
    tty: true
    volumes:
      - ../:/home/builder/workdir
      - ../../plugin-api:/home/builder/plugin-api:ro
  deb-console:
    image: debian13-builder
    working_dir: /home/builder/
    user: builder
    entrypoint: ["/home/builder/workdir/builder/debian-console.sh"]
    stdin_open: true
    tty: true
    volumes:
      - ../:/home/builder/workdir
      - ../../plugin-api:/home/builder/plugin-api:ro
  apt:
    image: debian13-builder
    working_dir: /home/builder
    user: builder
    entrypoint: ["/home/builder/workdir/builder/android.sh"]
    stdin_open: true
    tty: true
    volumes:
      - ../:/home/builder/workdir
      - ../../plugin-api:/home/builder/plugin-api:ro
  rpm:
    image: fedora41-builder
    working_dir: /home/builder
    user: builder
    entrypoint: ["/home/builder/workdir/builder/fedora-gtk.sh"]
    stdin_open: true
    tty: true
    volumes:
      - ../:/home/builder/workdir
      - ../../plugin-api:/home/builder/plugin-api:ro
  rpm-webserver:
    image: fedora41-builder
    working_dir: /home/builder
    user: builder
    entrypoint: ["/home/builder/workdir/builder/fedora-webserver.sh"]
    stdin_open: true
    tty: true
    volumes:
      - ../:/home/builder/workdir
      - ../../plugin-api:/home/builder/plugin-api:ro
  rpm-console:
    image: fedora41-builder
    working_dir: /home/builder
    user: builder
    entrypoint: ["/home/builder/workdir/builder/fedora-console.sh"]
    stdin_open: true
    tty: true
    volumes:
      - ../:/home/builder/workdir
      - ../../plugin-api:/home/builder/plugin-api:ro
  zst:
    image: arch-builder
    working_dir: /home/builder
    user: builder
    entrypoint: ["/home/builder/workdir/builder/arch-gtk.sh"]
    stdin_open: true
    tty: true
    volumes:
      - ../:/home/builder/workdir
      - ../../plugin-api:/home/builder/plugin-api:ro
  zst-webserver:
    image: arch-builder
    working_dir: /home/builder
    user: builder
    entrypoint: ["/home/builder/workdir/builder/arch-webserver.sh"]
    stdin_open: true
    tty: true
    volumes:
      - ../:/home/builder/workdir
      - ../../plugin-api:/home/builder/plugin-api:ro
  zst-console:
    image: arch-builder
    working_dir: /home/builder
    user: builder
    entrypoint: ["/home/builder/workdir/builder/arch-console.sh"]
    stdin_open: true
    tty: true
    volumes:
      - ../:/home/builder/workdir
      - ../../plugin-api:/home/builder/plugin-api:ro
  exe:
    image: msys-builder
    working_dir: /home/builder
    user: builder
    entrypoint: ["/home/builder/workdir/builder/wine-msys-gtk.sh"]
    stdin_open: true
    tty: true
    volumes:
      - ../:/home/builder/workdir/
      - ../../plugin-api:/home/builder/plugin-api:ro
  exe-webserver:
    image: msys-builder
    working_dir: /home/builder
    user: builder
    entrypoint: ["/home/builder/workdir/builder/wine-msys-webserver.sh"]
    stdin_open: true
    tty: true
    volumes:
      - ../:/home/builder/workdir/
      - ../../plugin-api:/home/builder/plugin-api:ro
  exe-console:
    image: msys-builder
    working_dir: /home/builder
    user: builder
    entrypoint: ["/home/builder/workdir/builder/wine-msys-console.sh"]
    stdin_open: true
    tty: true
    volumes:
      - ../:/home/builder/workdir/
      - ../../plugin-api:/home/builder/plugin-api:ro
